### ISSUE TITLE
I still dont have access 

### ISSUE THREAD

**Issue by rawsewage38** [Galahadagent/My-projects-in-mindustry#3]
![Screenshot_20240427-133949](https://github.com/Galahadagent/My-projects-in-mindustry/assets/97264396/f9debbe4-def6-46e9-b371-78283578cea6)

**Comment by Galahadagent** [comment]
How can  I give you the access?
I'm a newbie in GitHub. Idk too much about it.
Can you explain me?

**Comment by rawsewage38** [comment]
Im not sure. I dont own a repostitory personally

**Comment by Galahadagent** [comment]
![Screenshot_2024-04-30-19-54-33-505_com android chrome](https://github.com/Galahadagent/My-projects-in-mindustry/assets/161305918/1fff926a-2f0c-4b18-b422-361506fb692f)
@rawsewage38 I have invited you as the collaborator of this repository.

**Comment by Galahadagent** [comment]
Timeout!!!
Sorry, you hadn't done anything.
You will not be selected as the collaborator of this repository. 😞

**Comment by Galahadagent** [comment]
> Timeout!!! Sorry, you hadn't done anything. You will not be selected as the collaborator of this repository. 😞


![Screenshot_2024-05-05-16-17-05-257_com android chrome](https://github.com/Galahadagent/My-projects-in-mindustry/assets/161305918/df9d108b-f7e1-4eea-8a90-2147de1f9998)
