### ISSUE TITLE
Uhh what did i miss.

### ISSUE THREAD

**Issue by kennarddh** [Galahadagent/My-projects-in-mindustry#4]
@Galahadagent i didn't check my github notification for like a week or 2

Is ur map done?

**Comment by Galahadagent** [comment]
And I haven't started for it's next update due to I am waiting for players feedback, etc.

**Comment by kennarddh** [comment]
@Galahadagent ok ill add it when i can or maybe ask bread to do it

**Comment by Galahadagent** [comment]
> @Galahadagent ok ill add it when i can or maybe ask bread to do it

Bread...... 🤔  I shall tell him.
